### ISSUE TITLE
Column of type Point using Postgis extension receives an error of invalid type

### ISSUE THREAD

**Issue by bryce-palmer** [ArsenyYankovsky/typeorm-aurora-data-api-driver#158]
**Package versions and database engine type (please complete the following information):**
 - Database Engine: postgresql11.13
 - TypeORM Version: 0.3.16
 - Driver Version: 2.4.4

**Describe the bug**
I am unable to add spatial data to my aurora postgresql database with the Postgis extension. I am specifically trying to add a Column of a type Point, but I get the error:

>   Error: 'param_5' is an invalid type
>        at error (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:40:9)
>        at formatType (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:236:28)
>        at formatParam (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:172:46)
>        at <anonymous> (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:157:20)
>        at Array.reduce (<anonymous>)
>        at processParams (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:143:29)       
>        at query (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:402:43)
>        at Object.query (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\node_modules\data-api-client\index.js:605:22)        
>        at DataApiDriver2.<anonymous> (C:\XXXXXXXXXXX\node_modules\typeorm-aurora-data-api-driver\src\typeorm-aurora-data-api-driver.ts:45:36)
>        at step (C:\XXXXXXXXXXX\node_modules\aws-sdk\lib\aws.js:11:18)

**To Reproduce**
Follow the answer to create from this Stackoverflow answer
https://stackoverflow.com/questions/67435650/storing-geojson-points-and-finding-points-within-a-given-distance-radius-nodej

**Comment by bryce-palmer** [comment]
I was never able to resolve this issue, might anyone have any advice? I did update to the 3.0.0 version of this driver but still experience the same problem.
