### ISSUE TITLE
UnsupportedResultException with Aurora Serverless V2

### ISSUE THREAD

**Issue by ryanmargono** [ArsenyYankovsky/typeorm-aurora-data-api-driver#164]
I am constantly getting `UnsupportedResultException: The result contains the unsupported data type regtype`.
Using the same postgres engine and version as when my Aurora Serverless V1.
Any suggestions?

**Comment by ArsenyYankovsky** [comment]
Please read the list of supported column types in the official document [here](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html). The `UnsupportedResultException` is thrown from the AWS SDK itself.

**Comment by ryanmargono** [comment]
Hey @ArsenyYankovsky, I read through that prior to migration and I confirmed through the RDS query editor that there are no unsupported types in my schema. 

Furthermore, RDS query editor (which uses Data API under the hood) works flawlessly. This leads me to believe there could be something wrong with the lib.

**Comment by vin1627** [comment]
the same issue that I've encountered. Im using typeorm then connect to Data API. at first run of the database it was successfully update/ migrate my schema after that it will show the error
<img width="1017" alt="image" src="https://github.com/ArsenyYankovsky/typeorm-aurora-data-api-driver/assets/34268875/a5167f1d-2f80-45b2-a1c2-b35efc6d6070">

**Comment by ficzusistvan** [comment]
Hi! I'm experiencing the same issue. I tried registering a type parser:
`const registerCustomTypeParsers = () => {
  types.setTypeParser(2206, (val) => {
    console.log({ val })
    return val
  }) // 2206 is the OID for regtype
}
`, but with no luck. Any suggestions?

**Comment by vin1627** [comment]
I've only encountered this when I used dataAPI.

**Comment by ficzusistvan** [comment]
Thanks @vin1627 ! Directly accessing the underlying postgres db solved the issue.
I was trying to generate/run migrations when I encountered this error. 
The ugly solution for me is to use a DataSource without Data API for migrations, the problem in this case is that the db must be publicly accessible..

**Comment by trendafil-gechev** [comment]
Unfortunately, this issue is still present and reproducible only through TypeORM and this driver. Executing the exact same SQL statement, which fails through the ORM, directly via the AWS CLI, Python SDK and JavaScript SDK returns expected result and the error is not present.
I am reproducing it by simply running `npx ts-node ./node_modules/typeorm/cli schema:sync -d ./typeorm-config.js`, stack trace looks like this:
```
Error during schema synchronization:
UnsupportedResultException: The result contains the unsupported data type regtype.
    at de_UnsupportedResultExceptionRes (/home/tgechev/tg/packages-layer/nodejs/node18/node_modules/typeorm-aurora-data-api-driver/node_modules/@aws-sdk/client-rds-data/dist-es/protocols/Aws_restJson1.js:699:23)
    at de_ExecuteStatementCommandError (/home/tgechev/tg/packages-layer/nodejs/node18/node_modules/typeorm-aurora-data-api-driver/node_modules/@aws-sdk/client-rds-data/dist-es/protocols/Aws_restJson1.js:432:25)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/tgechev/tg/packages-layer/nodejs/node18/node_modules/typeorm-aurora-data-api-driver/node_modules/@smithy/middleware-serde/dist-es/deserializerMiddleware.js:4:24
    at async /home/tgechev/tg/packages-layer/nodejs/node18/node_modules/typeorm-aurora-data-api-driver/node_modules/@aws-sdk/middleware-signing/dist-es/awsAuthMiddleware.js:26:20
    at async /home/tgechev/tg/packages-layer/nodejs/node18/node_modules/typeorm-aurora-data-api-driver/node_modules/@smithy/middleware-retry/dist-es/retryMiddleware.js:27:46
    at async /home/tgechev/tg/packages-layer/nodejs/node18/node_modules/typeorm-aurora-data-api-driver/node_modules/@aws-sdk/middleware-logger/dist-es/loggerMiddleware.js:3:26
```
SQL statement in question looks like this:
```
SELECT "con"."conname" AS "constraint_name",
       "con"."nspname" AS "table_schema",
       "con"."relname" AS "table_name",
       "att2"."attname" AS "column_name",
       "ns"."nspname" AS "referenced_table_schema",
       "cl"."relname" AS "referenced_table_name",
       "att"."attname" AS "referenced_column_name",
       "con"."confdeltype" AS "on_delete",
       "con"."confupdtype" AS "on_update",
       "con"."condeferrable" AS "deferrable",
       "con"."condeferred" AS "deferred"
FROM ( SELECT UNNEST ("con1"."conkey") AS "parent",
              UNNEST ("con1"."confkey") AS "child",
	      "con1"."confrelid",
	      "con1"."conrelid",
	      "con1"."conname",
              "con1"."contype",
	      "ns"."nspname",
	      "cl"."relname",
	      "con1"."condeferrable",
	      CASE WHEN "con1"."condeferred" THEN 'INITIALLY DEFERRED' ELSE 'INITIALLY IMMEDIATE' END as condeferred,
	      CASE "con1"."confdeltype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confdeltype",
	      CASE "con1"."confupdtype" WHEN 'a' THEN 'NO ACTION' WHEN 'r' THEN 'RESTRICT' WHEN 'c' THEN 'CASCADE' WHEN 'n' THEN 'SET NULL' WHEN 'd' THEN 'SET DEFAULT' END as "confupdtype"
       FROM "pg_class" "cl"
       INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid"
       INNER JOIN "pg_constraint" "con1" ON "con1"."conrelid" = "cl"."oid"
	         WHERE "con1"."contype" = 'f' AND (("ns"."nspname" = 'public' AND "cl"."relname" = '<table-name-1>')
			                        OR ("ns"."nspname" = 'public' AND "cl"."relname" = '<table-name-2>')
				                OR ("ns"."nspname" = 'public' AND "cl"."relname" = '<table-name-...>')
						OR ("ns"."nspname" = 'public' AND "cl"."relname" = '<table-name-N>')) ) "con"
       INNER JOIN "pg_attribute" "att" ON "att"."attrelid" = "con"."confrelid" AND "att"."attnum" = "con"."child"
       INNER JOIN "pg_class" "cl" ON "cl"."oid" = "con"."confrelid"  AND "cl"."relispartition" = 'f'
       INNER JOIN "pg_namespace" "ns" ON "cl"."relnamespace" = "ns"."oid"
       INNER JOIN "pg_attribute" "att2" ON "att2"."attrelid" = "con"."conrelid" AND "att2"."attnum" = "con"."parent"
```
Tested and working AWS CLI command:
```
aws rds-data execute-statement --resource-arn "<cluster-arn>" \
--profile "<profile-name>" \
--database "postgres" \
--secret-arn "<secret-arn>" \
--sql "<same-big-sql-with-escaped-quotes>"
```
Tested and working Python SDK script:
```
import boto3

rdsData = boto3.client('rds-data')

response1 = rdsData.execute_statement(
    includeResultMetadata=True,
    resourceArn="<cluster-arn>",
    secretArn="<secret-arn>",
    database='postgres',
    sql="<same-big-sql-with-escaped-quotes>")

print(response1)

```
Tested and working JavaScript SDK script:
```
const { ExecuteStatementCommand, RDSDataClient } = require('@aws-sdk/client-rds-data');

(async function () {
  const client = new RDSDataClient({
    region: 'eu-central-1'
  });
  const command = new ExecuteStatementCommand({
    sql: `<same-big-sql>`,
    database: 'postgres',
    includeResultMetadata: true,
    continueAfterTimeout: false,
    resourceArn: "<cluster-arn>",
    secretArn: "<secret-arn>"
  });

  const resp = await client.send(command);

  console.log(JSON.stringify(resp));
})();

```
Tested on the following package versions:
- @aws-sdk/client-rds-data: 3.614.0
- typeorm: 0.3.20
- typeorm-aurora-data-api-driver: 3.0.1

Having no migrations like @ficzusistvan has pointed out and not being able to synchronize the database schema renders this driver unusable. This issue deserves more attention, @ArsenyYankovsky I am willing to help to further diagnose it if you need more input.

**Comment by marcofs** [comment]
I solved it by patching `typeorm`.

If you really need this to work, here's how you do it:
 1. Clone `typeorm`
     - `cd your-project`
     - `git clone https://github.com/typeorm/typeorm.git`
 2. Patch typeorm by changing `"regtype"` to `text` and package it
     - Find `your-project/typeorm/src/driver/postgres/PostgresQueryRunner.ts`
     - Change `('"' || "udt_schema" || '"."' || "udt_name" || '"')::"regtype" AS "regtype"` to `('"' || "udt_schema" || '"."' || "udt_name" || '"')::text AS "regtype"`
     - `npm install`
     - `npm run package`
3. Now your project will need to use this patched `typeorm`
    - Go to `your-project/package.json`
    - Set your `typeorm` dependency to read from the patched version: `"typeorm": "file:./typeorm/build/package`
    - `npm install`

**Comment by gshpychka** [comment]
@ArsenyYankovsky can you take another look at this, please? Does not seem like an issue with the underlying DB.

**Comment by ArsenyYankovsky** [comment]
As the workaround above suggests, the fix needs to be done in the typeorm repo.
I'll check later this week if I can create a PR to typeorm to get this fixed.

**Comment by ArsenyYankovsky** [comment]
I submitted a PR witha fix to the TypeORM repository [here](https://github.com/typeorm/typeorm/pull/11568).
