### ISSUE TITLE
typeorm-aurora-data-api-driver not present in zipped lambda sources

### ISSUE THREAD

**Issue by spolom** [ArsenyYankovsky/typeorm-aurora-data-api-driver#59]
While researching TypoORM with AWS' Data API, I ran into the bellow error (simple serverless lambda w/ TypeScript). typeorm-aurora-data-api-driver is not present in the zipped lambda sources.

I am not sure whether it is related to this closed issue or a configuration error on my side.

```2021-01-18T16:41:16.410Z	e18a07b9-31ab-4496-a75b-43f7e30f991b	ERROR	Invoke Error 	
{
    "errorType": "Error",
    "errorMessage": "Cannot find module '/var/task/node_modules/typeorm-aurora-data-api-driver'\nRequire stack:\n- /var/task/node_modules/typeorm/platform/PlatformTools.js\n- /var/task/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js\n- /var/task/node_modules/typeorm/migration/MigrationExecutor.js\n- /var/task/node_modules/typeorm/connection/Connection.js\n- /var/task/node_modules/typeorm/connection/ConnectionManager.js\n- /var/task/node_modules/typeorm/index.js\n- /var/task/src/functions/hello/handler.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "code": "MODULE_NOT_FOUND",
    "requireStack": [
        "/var/task/node_modules/typeorm/platform/PlatformTools.js",
        "/var/task/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js",
        "/var/task/node_modules/typeorm/migration/MigrationExecutor.js",
        "/var/task/node_modules/typeorm/connection/Connection.js",
        "/var/task/node_modules/typeorm/connection/ConnectionManager.js",
        "/var/task/node_modules/typeorm/index.js",
        "/var/task/src/functions/hello/handler.js",
        "/var/runtime/UserFunction.js",
        "/var/runtime/index.js"
    ],
    "stack": [
        "Error: Cannot find module '/var/task/node_modules/typeorm-aurora-data-api-driver'",
        "Require stack:",
        "- /var/task/node_modules/typeorm/platform/PlatformTools.js",
        "- /var/task/node_modules/typeorm/driver/sqlserver/SqlServerDriver.js",
        "- /var/task/node_modules/typeorm/migration/MigrationExecutor.js",
        "- /var/task/node_modules/typeorm/connection/Connection.js",
        "- /var/task/node_modules/typeorm/connection/ConnectionManager.js",
        "- /var/task/node_modules/typeorm/index.js",
        "- /var/task/src/functions/hello/handler.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:687:27)",
        "    at Module.require (internal/modules/cjs/loader.js:903:19)",
        "    at require (internal/modules/cjs/helpers.js:74:18)",
        "    at Function.PlatformTools.load (/var/task/src/platform/PlatformTools.ts:130:20)",
        "    at AuroraDataApiPostgresDriver.loadDependencies (/var/task/src/driver/aurora-data-api-pg/AuroraDataApiPostgresDriver.ts:104:17)",
        "    at new AuroraDataApiPostgresDriver (/var/task/src/driver/aurora-data-api-pg/AuroraDataApiPostgresDriver.ts:56:14)",
        "    at DriverFactory.create (/var/task/src/driver/DriverFactory.ts:65:24)",
        "    at new Connection (/var/task/src/connection/Connection.ts:128:43)",
        "    at ConnectionManager.create (/var/task/src/connection/ConnectionManager.ts:64:28)"
    ]
}
```

This is the webpack config:

```const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');
const TsconfigPathsPlugin = require('tsconfig-paths-webpack-plugin');

module.exports = {
  context: __dirname,
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: slsw.lib.webpack.isLocal ? 'eval-cheap-module-source-map' : 'source-map',
  resolve: {
    extensions: ['.mjs', '.json', '.ts'],
    symlinks: false,
    cacheWithContext: false,
    plugins: [
      new TsconfigPathsPlugin({
        configFile: './tsconfig.paths.json',
      }),
    ],
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  optimization: {
    concatenateModules: false,
  },
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      {
        test: /\.(tsx?)$/,
        loader: 'ts-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: true,
        },
      },
    ],
  },
  plugins: [],
};
```

I'd appreciate any hint.

**Comment by spolom** [comment]
Could this be related to https://gitmemory.com/issue/typeorm/typeorm/4788/542529802?

**Comment by spolom** [comment]
`import 'typeorm-aurora-data-api-driver';` in the handler allows webpack to package the sources correctly.
