### ISSUE TITLE
date.getUTCFullYear is not a function

### ISSUE THREAD

**Issue by davingreen** [ArsenyYankovsky/typeorm-aurora-data-api-driver#74]
```
TypeError: date.getUTCFullYear is not a function
      at dateToDateTimeString (/opt/nodejs/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js:943:25)
      at PostgresQueryTransformer.preparePersistentValue (/opt/nodejs/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js:1181:32)
      at DataApiDriver.preparePersistentValue (/opt/nodejs/node_modules/typeorm-aurora-data-api-driver/dist/typeorm-aurora-data-api-driver.umd.js:1363:42)
      at AuroraDataApiPostgresDriver.preparePersistentValue (/opt/nodejs/node_modules/app/node_modules/typeorm/driver/aurora-data-api-pg/AuroraDataApiPostgresDriver.js:72:28)
      at /opt/nodejs/node_modules/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:365:57
      at Array.forEach (<anonymous>)
      at /opt/nodejs/node_modules/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:353:25
      at Array.forEach (<anonymous>)
      at UpdateQueryBuilder.createUpdateExpression (/opt/nodejs/node_modules/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:347:85)
      at UpdateQueryBuilder.getQuery (/opt/nodejs/node_modules/app/node_modules/typeorm/query-builder/UpdateQueryBuilder.js:45:21)
}
```

When trying to update:
```typescript
  @Column({ nullable: true, type: 'timestamp' })
  public scheduledToSendAt?: Date
```
using
```typescript
const announcement: IUpdateAnnouncement = {
    ...data,
    updatedAt: new Date(),
  }
const announcementRepo = connection.getRepository(Announcement)
await announcementRepo.save(announcement)
```

**Comment by davingreen** [comment]
I resolved this by transforming the scheduledToSendAt to date from a string. Apparently, the data api driver causes an issue with TypeORM's automatic casting of date strings to dates (maybe?)

Anyway, I've got a workaround -- thanks!

**Comment by davingreen** [comment]
Hi @tgechev,

Running latest updates, I was able to change the types back to Date. You can then use a JS Date object (instead of `new Date().toISOString()`, just `new Date()`. 

I've found that the `TypeError: date.getUTCFullYear is not a function` typically occurs when TypeORM is expecting a Date object, but receiving a string.

Hope that helps!
